// ui

export const REQUESTING = 'REQUESTING'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
export const REQUEST_FAILURE = 'REQUEST_FAILURE'

// home
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

// news
export const FETCH_NEWS_LIST_SUCCESS = 'FETCH_NEWS_LIST_SUCCESS'
export const FETCH_NEWS_LIST_FAILURE = 'FETCH_NEWS_LIST_FAILURE'
export const FETCH_MORE_NEWS_LIST_SUCCESS = 'FETCH_MORE_NEWS_LIST_SUCCESS'

